### ISSUE TITLE
Works with 2024.7.2 but not with 2025.9.2

### ISSUE THREAD

**Issue by m1k3f15h** [persuader72/esphome-components#27]
Hi

The component doesnt Work with the new Version of ESPHOME...
Any Tips for me?

`In file included from src/esphome/components/shelly_dallas/shelly_dallas_component.cpp:1:
src/esphome/components/shelly_dallas/shelly_dallas_component.h:65:15: error: 'std::string esphome::shelly_dallas::DallasTemperatureSensor::unique_id()' marked 'override', but does not override
   65 |   std::string unique_id() override;
      |               ^~~~~~~~~
*** [.pioenvs/esphome-spike/src/esphome/components/shelly_dallas/shelly_dallas_component.cpp.o] Error 1`

Mike

**Comment by m1k3f15h** [comment]
Works Great. 
Thank You 👍
